baseURL = "/"
languageCode = "en-us"
title = "Niklas site"
theme = "kube"
description = ""
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "salkin" # add your company name
  github = "salkin" # add your github profile name
  twitter = "" # add your twitter profile
  email = "niklas.wik@iki.fi"

[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Kneusa"
    weight = -100
    url = "/kneusa/"
